name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: fifth-coral-266414

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy stock_market --image gcr.io/fifth-coral-266414/my-node-app --platform managed --region asia-northeast1-a --allow-unauthenticated
